[package]
name = "ltpdr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1"
good_lp = { version = "0.3.2", features = ["highs"], default-features = false }